### ISSUE TITLE
Stopped working with latest nixpkgs?

### ISSUE THREAD

**Issue by Nairou** [wamserma/flake-programs-sqlite#6]
After updating `nixpkgs` today, I now get an error in `flake-programs-sqlite` on rebuild:

```
error: attribute 'f91ee3065de91a3531329a674a45ddcb3467a650' missing

       at /nix/store/dnkgqnx4gqz811qkl6fjaphd08w1nj4r-source/programs-sqlite.nix:3:10:

            2| let
            3|   meta = (lib.importJSON ./sources.json)."${rev}";
             |          ^
            4| in
(use '--show-trace' to show detailed location information)
```

I assume something is now out of date?

I'm new to NixOS, but happy to provide details.

**Comment by wamserma** [comment]
I just checked and you probably updated before the scraper could catch up with the channel bump.
The entry is now available (https://github.com/wamserma/flake-programs-sqlite/blob/f89d7d7b0affb1b8cf30462f1313ffe18e18ec23/sources.json#L4538) and things should be working on your side.

Can you confirm?

**Comment by Nairou** [comment]
Looks like that did the trick, thanks!

For some reason, I had to delete my `flake.lock` to get it to see the latest version.

**Comment by Nairou** [comment]
> Instead of deleting the lockfile you can do `nix flake update` or `nix flake lock --update-input flake-programs-sqlite`.

That is what I originally did, which is why I was confused about the error persisting. I'll have to ask on Discourse to see what understanding I'm missing. But I appreciate your help.
